name: publish-npm
on:
  push:
    branches:
      - develop
jobs:
  publish_npm:
    name: Push NPM Package
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install NPM Modules
        run: yarn

      - name: Build package
        run: yarn build

      - name: Copy package.json
        run: cp package.json ./dist

      - name: Copy readme
        run: cp README.md ./dist

      - name: Copy license
        run: cp LICENSE.md ./dist

      - name: Install only production dependencies
        run: yarn --prod

      - name: Remove Typescript folders
        run: rm -rf ./orm ./tsconfig.build.json ./tsconfig.json

      - name: Publish NPM Package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/package.json
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
